from solution.validator.error_validator import ErrorValidator


class Type5Validator(ErrorValidator):

    def validate(self, ae, cm, ae_df, cm_df):
        pass
